Add generator for Indonesian language
jzonta/FakerRestaurant pull request #6
Opened 2018-10-17 08:08 UTC by agasigp

2018-11-08 12:54 UTC, jzonta commented
@agasigp You changed en_US language, added language Indonesian in en_US. Please check your commit.

2018-11-09 03:26 UTC, agasigp commented
Ups, my bad. I just fixed that.

2019-02-11 18:41 UTC, jzonta commented on src/Provider/en_US/Restaurant.php
> -
The file did not have significant changes, it is not necessary to be sent, you must remove the modified line.

2019-02-11 18:43 UTC, jzonta requested changes
The file  "src/Provider/en_US/Restaurant.php"  did not have significant changes, it is not necessary to be sent, you must remove the modified line.

New names added. Could you do the translation?

2020-01-31 14:33 UTC, jzonta commented
Feche porque você não atendeu à solicitação de alteração e outro usuário enviou um PR iqual

2020-01-31 14:33 UTC, closed without merging